login/urls.py
from django.conf.urls import url

from main.views import profile
from . import views

app_name = 'login'
urlpatterns = [
    url(r'^$', views.sign_up, name='sign_up'),
    url(r'^signin/$', views.sign_in, name='sign_in'),
]

main/urls.py
from django.conf.urls import url

from . import views

app_name = 'main'
urlpatterns = [
    url(r'^(?P<username>[a-z]*)/$', views.profile, name='profile'),
]

radiant/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('login.urls')),
    url(r'^user/', include('main.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

login/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

main/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Connection(models.Model):
    user_one = models.ForeignKey(User, related_name='initiator', on_delete=models.CASCADE)
    user_two = models.ForeignKey(User, related_name='receiver', on_delete=models.CASCADE)
    one_to_two = models.TextField()
    two_to_one = models.TextField()

    def __str__(self):
        if self.is_valid:
            name_one = self.user_one.username
            name_two = self.user_two.username
            return "Connection between " + str(name_one) + " and " + str(name_two)
        else:
            return "The connection is no longer valid"

    def is_valid(self):
        return self.user_one.is_active and self.user_two.is_active


class Personal(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    current_value = models.IntegerField()
    friends = models.ManyToManyField(User, related_name='friend')

    def add_friend(self, friend):
        self.friends.add(friend)

login/views.py
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render


def index(request):
    return render(request, 'login/index.html', {})


def sign_up(request):
    if request.method == 'GET':
        return render(request, 'login/index.html', {})
    else:
        username = request.POST['username']
        password = request.POST['password']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        email = request.POST['email']

        if username and password and first_name and last_name and email:
            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name
            user.save()

            return HttpResponseRedirect("user/%s/" % username)
        else:
            return render(request, 'login/index.html', {
                'error_message': "Please fill out all blanks",
            })


def sign_in(request):
    if request.method == 'GET':
        return render(request, 'login/signin.html', {})
    else:
        try:
            username = request.POST['username']
            password = request.POST['password']
        except KeyError:
            return render(request, 'login/signin.html', {
                'error_message': "Signin information is incorrect",
            })
        else:
            user = authenticate(username=username, password=password)
            if user is not None:
                return HttpResponseRedirect("../user/%s/" % username)
            else:
                return render(request, 'login/signin.html', {
                    'error_message': "Signin information is incorrect",
            })


def temp(reqeust, username):
    return HttpResponse("good!")

main/views.py
from django.contrib.auth.models import User
from django.http import Http404
from django.shortcuts import render

from main.models import Personal
from .populate import feed


def profile(request, username):
    user = User.objects.get(username=username)
    if not hasattr(user, 'personal'):
        user.personal = Personal()

    if user.is_authenticated():
        json_data = feed()
        return render(request, 'main/profile.html', {
            'first_name': user.first_name,
            'json_data': json_data,
        })
    else:
        raise Http404("This page does not exist")

login/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <title>Radiant - have a lovely day</title>
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="Bodo - Simple One Page Personal" name="description">
    <meta content="BdgPixel" name="author">

    <!--styles-->
    <link href="{% static "login/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "login/css/owl.carousel.css" %}" rel="stylesheet">
    <link href="{% static "login/css/owl.theme.css" %}" rel="stylesheet">
    <link href="{% static "login/css/magnific-popup.css" %}" rel="stylesheet">
    <link href="{% static "login/css/style.css" %}" rel="stylesheet">
    <link href="{% static "login/css/responsive.css" %}" rel="stylesheet">
    
    <!--fonts google-->
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500,700' rel='stylesheet' type='text/css'>
    
    <!--[if lt IE 9]>
       <script type="text/javascript" src="js/html5shiv.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <!--PRELOADER-->
    <div id="preloader">
      <div id="status">
        <img alt="logo" src="{% static "login/images/logo.png" %}">
      </div>
    </div>
    <!--/.PRELOADER END-->

    <!--HEADER -->
    <div class="header">
      <div class="for-sticky">
        <!--LOGO-->
        <div class="col-md-2 col-xs-6 logo">
          <a href="{% url 'login:sign_up' %}"><img alt="logo" class="logo-nav" src="{% static "login/images/logo.png" %}"></a>
        </div>
        <!--/.LOGO END-->
      </div>
      <div class="menu-wrap">
        <nav class="menu">
          <div class="menu-list">
            <a data-scroll="" href="#home" class="active">
              <span>Home</span>
            </a>
            <a data-scroll="" href="#about">
              <span>About</span>
            </a>
            <a data-scroll="" href="#contact">
              <span>Sign Up</span>
            </a>
          </div>
        </nav>
        <button class="close-button" id="close-button">Close Menu</button>
      </div>
      <button class="menu-button" id="open-button">
        <span></span>
        <span></span>
        <span></span>
      </button><!--/.for-sticky-->
    </div>
    <!--/.HEADER END-->
    
    <!--CONTENT WRAP-->
    <div class="content-wrap">
      <!--CONTENT-->
      <div class="content">
        <!--HOME-->
        <section id="home">
          <div class="container">
            <div class="row">
              <div class="wrap-hero-content">
                  <div class="hero-content">
                    <h1>Radiant</h1>
                    <br>
                    <span class="typed"></span>
                  </div>
              </div>
              <div class="mouse-icon margin-20">
                <div class="scroll"></div>
              </div>
            </div>
          </div>
        </section>
        <!--/.HOME END-->

        <!--ABOUT-->
        <section id="about">
          <div class="col-md-6 col-xs-12 no-pad">
            <div class="bg-about"></div>
          </div>
          <div class="col-md-6 col-sm-12 col-xs-12 white-col">
            <div class="row">
              <!--OWL CAROUSEL2-->
              <div class="owl-carousel2">
                <div class="col-md-12">
                  <div class="wrap-about">
                    <div class="w-content">
                      <p class="head-about">
                        “What happens when people open their hearts?"
                        "They get better.” 
                      </p>
                      
                      <h5 class="name">
                        Haruki Murakami, Norwegian Wood
                      </h5>
                    </div>
                  </div>
                </div>

                <div class="col-md-6 col-sm-12 col-xs-12 white-col">
                  <div class="row">
                    <!--OWL CAROUSEL2-->
                    <div class="owl-carousel2">
                      <div class="col-md-12">
                        <div class="wrap-about">
                          <div class="w-content">
                            <p class="head-about">
                               “The wound is the place where the Light enters you.” 
                            </p>

                            <h5 class="name">
                              Rumi
                            </h5>
                          </div>
                        </div>
                      </div>    
                </div>
              </div>
              <!--/.OWL CAROUSEL2 END-->
            </div>
          </div>
        </section>
        <!--/.ABOUT END-->

        <!--SIGNUP-->
        <section id="contact" class="white-bg">
          <div class="container">
            <div class="row">
              <div class="col-md-3">
                <h3 class="title-small">
                  <span>Sign Up</span>

                </h3>
                <p class="head-about">
                   “You've gotta dance like there's nobody watching,"
                    "Love like you'll never be hurt,"
                    "Sing like there's nobody listening,"
                    "And live like it's heaven on earth.”  
                </p>

                <h5 class="name">
                  William W. Purkey
                </h5>

              </div>
              <div class="col-md-9 content-right">
                <form action="{% url 'login:sign_up' %}" method="post">
                {% csrf_token %}
                  <div class="group">
                    <input required="" type="text" name="firstname"><span class="highlight"></span><span class="bar"></span><label>First Name</label>
                  </div>
                  <div class="group">
                    <input required="" type="text" name="lastname"><span class="highlight"></span><span class="bar"></span><label>Last Name</label>
                  </div>
                  <div class="group">
                    <input required="" type="text" name="username"><span class="highlight"></span><span class="bar"></span><label>Username</label>
                  </div>
                  <div class="group">
                    <input required="" type="password" name="password"><span class="highlight"></span><span class="bar"></span><label>Password</label>
                  </div>
                  <div class="group">
                    <input required="" type="password" name="password_retype"><span class="highlight"></span><span class="bar"></span><label>Retype Password</label>
                  </div>
                  <div class="group">
                    <input required="" type="email" name="email"><span class="highlight"></span><span class="bar"></span><label>Email</label>
                  </div>
                  <input id="signUp" name="signUp" type="submit" value="Sign Up">
                </form>
              </div>
            </div>
          </div>
            <a href="{% url 'login:sign_in' %}">Already have an account? Sign in here</a>
        </section>
        <!--/.CONTACT END-->
        
        <!--FOOTER-->
        <footer>
          <div class="footer-top">
            <ul class="socials">
              <li class="facebook">
                <a href="#" data-hover="Facebook">Facebook</a>
              </li>
              <li class="twitter">
                <a href="#" data-hover="Twitter">Twitter</a>
              </li>
              <li class="gplus">
                <a href="#" data-hover="Google +">Google +</a>
              </li>
            </ul>
          </div>
        </footer>
        <!--/.FOOTER-END-->

      <!--/.CONTENT END-->
      </div>
    <!--/.CONTENT-WRAP END-->
    </div>
    
    <script src="{% static "login/js/jquery-1.9.1.min.js" %}" type="text/javascript"></script>
    <script src="{% static "login/js/jquery.appear.js" %}" type="text/javascript"></script>
    <script src="{% static "login/js/bootstrap.min.js" %}" type="text/javascript"></script>
    <script src="{% static "login/js/classie.js" %}" type="text/javascript"></script>
    <script src="{% static "login/js/owl.carousel.min.js" %}" type="text/javascript"></script>
    <script src="{% static "login/js/jquery.magnific-popup.min.js" %}" type="text/javascript"></script>
    <script src="{% static "login/js/masonry.pkgd.min.js" %}" type="text/javascript"></script>
    <script src="{% static "login/js/masonry.js" %}" type="text/javascript"></script>
    <script src="{% static "login/js/smooth-scroll.min.js" %}" type="text/javascript"></script>
    <script src="{% static "login/js/typed.js" %}" type="text/javascript"></script>
    <script src="{% static "login/js/main.js" %}" type="text/javascript"></script>
  </body>
</html>

login/templates/login/plain_index.html
<!DOCTYPE html>
<head></head>
<body>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'login:sign_up' %}" method="post">
    {% csrf_token %}
        First Name:<br>
        <input type="text" name="firstname">
        <br>
        Last Name:<br>
        <input type="text" name="lastname">
        <br>
        Username:<br>
        <input type="text" name="username">
        <br>
        Password:<br>
        <input type="password" name="password">
        <br>
        Retype Password:<br>
        <input type="password" name="password_retype">
        <br>
        Email:<br>
        <input type="email" name="email">
        <br>
        <input type="submit" value="Sign Up">
    </form>
    <a href="{% url 'login:sign_in' %}">Already have an account? Sign in here</a>
</body>

login/templates/login/signin.html
<!DOCTYPE html>
<head></head>
<body>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'login:sign_in' %}" method="post">
    {% csrf_token %}
        Username:<br>
        <input type="text" name="username">
        <br>
        Password:<br>
        <input type="password" name="password">
        <br>
        <input type="submit" value="Sign In">
    </form>
</body>

main/templates/main/profile.html
<!DOCTYPE html>
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static "main/main.css" %}">
    <script src="https://d3js.org/d3.v3.min.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
</head>
<body>
    <div><h1>Welcome, {{ first_name }}</h1></div>

    <div class="network">
        <script src="{% static "main/network.js" %}"></script>
        <script>
            var data = jQuery.parseJSON('{{ json_data }}');
            /* SVG frame creation */
            var w = 1290,
                    h = 600,
                    fbBlue = d3.rgb("#3b5998"),
                    fill = [fbBlue.brighter(2), fbBlue.brighter(), fbBlue, fbBlue.darker()];

            var vis = d3.select("body").append("svg:svg")
                    .attr("width", w)
                    .attr("height", h);

            var nodes = data.nodes;

            var links = data.links;

            var force = d3.layout.force()
                    .charge(-80)
                    .linkDistance(function(d) {
                        return (Math.random() * (400 - 200))
                    })
                    .linkStrength(0.2)
                    .size([w, h])
                    .nodes(nodes)
                    .links(links)
                    .start();

            /*Link creation template */
            var link = vis.selectAll(".link")
                    .data(links)
                    .enter()
                    .append("line")
                    .attr("class", "link");

            /*Node creation template */
            var node = vis.selectAll("circle.node")
                    .data(nodes)
                    .enter().append("svg:circle")
                    .attr("class", "node")
                    .attr("id", function(d) {
                        return d.index;
                    })
                    .attr("cx", function(d) {
                        return d.x;
                    }) //x
                    .attr("cy", function(d) {
                        return d.y;
                    }) //y
                    .attr("r", function(d) {
                        return d.size;
                    })
                    .style("fill", function(d) {
                        var color;
                        if (d.value == 1) {
                            color = "rgb(0,0,139)";
                        }
                        if (d.value == 2) {
                            color = "rgb(30,144,255)";
                        }
                        if (d.value == 3) {
                            color = "rgb(50,205,50)";
                        }
                        if (d.value == 4) {
                            color = "rgb(154,205,50)";
                        }
                        if (d.value == 5) {
                            color = "rgb(255,215,0)";
                        }
                        return color;
                    })
                    .call(force.drag);

             /* Start transition */
            vis.style("opacity", 1e-6)
                    .transition()
                    .duration(1000)
                    .style("opacity", 1);

            //Forces in action
            force.on("tick", function(e) {
                link.attr("x1", function(d) {
                            return d.source.x;
                        })
                        .attr("y1", function(d) {
                            return d.source.y;
                        })
                        .attr("x2", function(d) {
                            return d.target.x;
                        })
                        .attr("y2", function(d) {
                            return d.target.y;
                        });

                node.attr("cx", function(d) {
                            return d.x;
                        })
                        .attr("cy", function(d) {
                            return d.y;
                        });
            });

            /* Click-plosion and tooltip*/
            d3.select("body").on("dblclick", function() {
                nodes.forEach(function(o, i) {
                    o.x += (Math.random() - .5) * 200;
                    o.y += (Math.random() - .5) * 200;
                });
                force.resume();
            });

            d3.select(d3.selectAll(".node")[0][0])
                    .style("stroke-width", 2)
                    .style("stroke", "yellow");


            d3.selectAll('.node').on('click', function() {
                var d3this = d3.select(this);
                if (d3.select(this).datum().index == 0) {
                    d3this.style("fill", "green");
                } else {
                    d3this.style("fill", "orange");
                }
                d3.event.stopPropagation();
            });

            d3.selectAll(".node").on("dblclick", function(d, i) {
                d.fixed = !d.fixed;
                d3.event.stopPropagation();
            });
            var div = d3.select("div.tooltip");
            d3.selectAll(".node").on("mouseover", function(d, i) {
                div.style("visibility", "visible")
                        .transition()
                        .duration(200)
                        .style("opacity", .9);
                var html;
                html = d.username;
                div.html(html)
                        .style("left", (d.x) + "px")
                        .style("top", (d.y) + "px");
            }).on("mouseout", function(d, i) {
                div.transition()
                        .duration(500)
                        .style("opacity", 0)
                        .each("end", function() {
                            div.style("visibility", "hidden")
                        });

            });
        </script>
    </div>

    <div class="control_panel">
        <p>This is the control panel</p>
    </div>
</body>